[package]
name = "keebgrab"
version = "0.0.2"
edition = "2021"
description = "Simple X11 keylogger"

authors = [
    "vdo <vdo1138@rbx.run>",
]

[dependencies.x11]
version = "2.21.0"
features = ["xlib", "xinput"]

